apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-s3-access
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::088317451471:role/eks-oidc-role"
---
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: aws-s3-access
  containers:
  - image: amazon/aws-cli
    name: aws-cli
    command: ["/bin/bash", "-c", "--"]
    args: ["while true;do sleep 30; done;"]